### ISSUE TITLE
Compiling requires README file which is not present

### ISSUE THREAD

**Issue by Psibur** [0xxon/bro-plugin-roca#1]
Per the subject.  Once I added a README file, compilation continued.

**Comment by 0xxon** [comment]
Fixed in bee080afdb8706ff4c5ca4b8bf67b72a659f0c7e

**Comment by pozgo** [comment]
Maybe release new version `0.0.1-1` with a fix so we don't need to specify exact commit hash. 

It's been a while since the last release.
