### ISSUE TITLE
Running bro with roca plugin causes segfault

### ISSUE THREAD

**Issue by Psibur** [0xxon/bro-plugin-roca#3]
OS: RHEL7.5 (fully updated 2018.06.26)
gcc: 4.8.5
gmp/gmp-devel: 6.0.0, release: 15.el7

Starting bro causes Segmentation Fault.

Please let me know if there's any further info you need.

**Comment by 0xxon** [comment]
Hi,

could you please let me know which version of bro you are running - if it is a version from git, the exact commit-hash would be nice. I assume you installed Bro from source?

Could you also potentially provide a backtrace of Bro, running Bro with gdb --args bro [command-line arguments] and then just issung "bt" when it crashes.

**Comment by Psibur** [comment]
Sorry for the late reply.  This was using bro 2.5.4 direct source download
from their website.  I'm also going to try with 2.5.5 as soon as time
allows.

Let me also try the backtrace and post results once finished.

**Comment by Psibur** [comment]
This is compiled inside a Docker container using RHEL 7.5 base OS.  Here
are the issues seen when running broctl with ROCA plugin installed:

When running bro with Roca plugin compiled in:

 docker exec -it bro /opt/bro/bin/broctl deploy
checking configurations ...
logger scripts failed.
/opt/bro/share/broctl/scripts/check-config: line 50:    74 Segmentation
fault      (core dumped) "${bro}" $check_option "$@"

manager scripts failed.
/opt/bro/share/broctl/scripts/check-config: line 50:    77 Segmentation
fault      (core dumped) "${bro}" $check_option "$@"

proxy-1 scripts failed.
/opt/bro/share/broctl/scripts/check-config: line 50:    80 Segmentation
fault      (core dumped) "${bro}" $check_option "$@"

worker-1-1 scripts failed.
/opt/bro/share/broctl/scripts/check-config: line 50:    82 Segmentation
fault      (core dumped) "${bro}" $check_option "$@"

-----

[root@ bro254]# cat /opt/bro/share/broctl/scripts/check-config
#!/usr/bin/bash
#
# Check Bro's configuration for errors.
#
# check-config <use_installed_policies> <print_loaded_scripts> <cwd>
<bro_opts>
#
# use_installed_policies:  1 to use local policy files installed by
#                          "broctl install", or 0 to use the original files
# print_loaded_scripts:  1 to output loaded_scripts.log, or 0 to not output
# cwd:  directory name to run Bro from
# bro_opts:  string containing Bro cmd-line options

if [ $# -lt 4 ]; then
    echo "check-config: missing arguments"
    exit 1
fi

. `dirname $0`/broctl-config.sh

use_installed_policies=$1
print_loaded_scripts=$2
tmp_node_dir=$3
shift 3

. "${scriptsdir}"/set-bro-path
if [ $? -ne 0 ]; then
    exit 1
fi

if [ ! -f "${bro}" ]; then
    echo "check-config: file not found: ${bro}"
    exit 1
fi

export PATH=${bindir}:${scriptsdir}:$PATH

cd "$tmp_node_dir"
if [ $? -ne 0 ]; then
    exit 1
fi

echo $@ >.cmdline

check_option="-a"
if [ "$print_loaded_scripts" = "1" ]; then
    # No bro logs are created with "-a", so don't use it with "broctl
scripts".
    check_option=
fi

# vvv this is where the output complains vvv
"${bro}" $check_option "$@"
rc=$?

if [ $rc -eq 0 ] && [ "$print_loaded_scripts" = "1" ]; then
    grep -v '^#' loaded_scripts*
fi

exit $rc

-------------------

[root@ /]# /opt/bro/bin/bro
Segmentation fault (core dumped)
[root@ /]# gdb -args /opt/bro/bin/bro
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/bro/bin/bro...(no debugging symbols found)...done.
(gdb) bt
No stack.
(gdb)

**Comment by 0xxon** [comment]
Hi,

thanks a lot for this. When running with gdb, could you do a "r" first, that should then cause the segfault, which will actually give a backtrace? :)

Or - alternatively you should be able to call gdb with gdb [path to bro] [path to coredump] which also should show the backtrace.

Thanks a lot,
 Johanna
